name: Python

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          python -m pip install --upgrade pip
          pip install opencv-python pyinstaller
      - name: build exe
        run: |
          pyinstaller -F fireWork.spec

      - name: publish exe
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.PINKTU_PYTHON }}
        run: |
          git config --global user.name 'pinktu'
          git config --global user.email 'chenbiuxiu@gmail.com'
          git pull
          git checkout publish
          mv dist/* .
          rm -rf __pycache__ build dist
          git add *
          git commit -m 编译执行文件
          git push
